README 파일을 수정하라
CodeSoom/DDD-Kurly-Clone-Promotion pull request #30
Opened 2021-10-16 06:55 UTC by eastshine-high

README는 디스커션에 의견 주신 것을 최대한 반영해서 뼈대를 잡아봤습니다. 프로젝트 진행하면서 내용을 채워보겠습니다.

2021-10-16 07:00 UTC, hannut91 commented
풀 리퀘스트 제목이 아쉽습니다. 풀 리퀘스트의 제목에는 작업의 내용이 아닌, 목적을 작성하는게 좋습니다. 

`수정`이라는 말은 너무 많은 의미로 해석될 수 있습니다. 변경을 한것도 수정이고, 삭제도 수정이고, 추가한 것도 수정이라고 해석될 수 있고 여러가지 의미로 해석될 수 있습니다.

아마도 이 작업에 여러 작업이 함께 있어서 그런 것 같아요. 만약 README에 유비쿼터스 언어만 추가 했다면

`README에 유비쿼터스 언어를 추가하라`라고 되었겠죠

2021-10-16 07:06 UTC, etff requested changes
고생하셨습니다. 몇가지 생각해볼만한 코멘트를 남겼습니다.

문서를 추가로 작업해주는 것도 좋지만 연습이라고 생각하고
처음에 잘 정리해두면 인수인계를 받는 사람이 많은 도움을 받을 수 있을 것같습니다.

2021-10-16 07:28 UTC, eastshine-high commented
> 풀 리퀘스트 제목이 아쉽습니다. 풀 리퀘스트의 제목에는 작업의 내용이 아닌, 목적을 작성하는게 좋습니다.
> 
> `수정`이라는 말은 너무 많은 의미로 해석될 수 있습니다. 변경을 한것도 수정이고, 삭제도 수정이고, 추가한 것도 수정이라고 해석될 수 있고 여러가지 의미로 해석될 수 있습니다.
> 
> 아마도 이 작업에 여러 작업이 함께 있어서 그런 것 같아요. 만약 README에 유비쿼터스 언어만 추가 했다면
> 
> `README에 유비쿼터스 언어를 추가하라`라고 되었겠죠

네 풀 리퀘스트의 제목은 목적을 작성하는 게 좋군요. 수정이란 표현은 조심해서 사용해야 겠네요. 감사합니다!

2021-10-17 04:08 UTC, hannut91 approved these changes

2021-10-24 05:30 UTC, etff approved these changes

2021-11-01 13:55 UTC, closed without merging