할인 목록을 조회하라
CodeSoom/DDD-Kurly-Clone-Promotion pull request #31
Opened 2021-10-16 07:45 UTC by hannut91

저장되어있는 할인 목록을 반환하는 getDiscounts를 만들었습니다.
할인 목록을 조회할 수 있도록 DiscountController를 만들었습니다. `GET /discounts`로 요청하면, 할인 목록을 응답합니다.

2021-10-16 10:22 UTC, etff requested changes
고생하셨습니다. 생각해볼만한 코멘트를 남겼는데 확인부탁드립니다.

2021-10-23 09:13 UTC, etff requested changes
고생하셨습니다! 생각해볼만한 코멘트를 남겼습니다

2021-10-23 09:13 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountData.java
> +@NoArgsConstructor
@Data 를 써보면 어떨까요?

2021-10-23 09:13 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountList.java
> +    }
DiscountList는 도메인 객체일까요?

2021-10-23 09:13 UTC, etff commented on src/test/java/com/kurly/promotion/ui/DiscountListTest.java
> +}
파일 끝은 공백을 생성해주세요

2021-10-23 09:13 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountList.java
> +    }
이 클래스가 도메인이라면 도메인이 DTO에 의존하고 있습니다.

굳이 클래스를 생성하는 것보다 DTO에서 변환해보면 어떨까요?

2021-10-23 09:13 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountList.java
> +    private final List<Discount> discountList;
클래스나 메서드 이름에 자료형을 넣는 것보다 복수형으로 표현해보면 어떨까요?

2021-10-23 09:13 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountDataMapper.java
> +}
메퍼 활용 좋습니다 👍

2021-10-23 09:13 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountData.java
> +    Long productId;
접근 제어자는 없어도 되는걸까요?

2021-10-23 09:19 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountController.java
> +        return discountList.list();
해당 메서드가 무엇을 하는지 예측하기 힘듭니다. 
동사를 사용해서 어떤 행위를 하는지 표현해보면 어떨까요?

2021-10-23 09:36 UTC, hannut91 commented on src/main/java/com/kurly/promotion/ui/DiscountList.java
> +    }
도메인 객체는 아니고, 응답 객체 생성을 위한 객체인데 무엇이 잘못되었을까요?

2021-10-23 09:37 UTC, hannut91 commented on src/main/java/com/kurly/promotion/ui/DiscountData.java
> +    Long productId;
private으로 명시해야겠습니다

2021-10-23 09:39 UTC, hannut91 commented on src/main/java/com/kurly/promotion/ui/DiscountController.java
> +        return discountList.list();
이 메서드가 그냥 `list내놔` 라고 하는거라서, 제가보기에는 괜찮아 보이는데 다른 좋은 이름을 제안해주실 수 있나요?

2021-10-23 09:43 UTC, hannut91 commented on src/main/java/com/kurly/promotion/ui/DiscountData.java
> +@NoArgsConstructor
적용했습니다 감사합니다 ㅎㅎ

2021-10-23 10:11 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountList.java
> +    }
도메인의 1급 컬렉션을 발견하면 도메인 내에서 무언가를 한다고 기대를 하게됩니다.

하지만 구현하신 내용을 보면 DTO를 만들어내는 행위를 하고 있습니다. 
도메인에서 DTO를 만드는 건 도메인의 역할이 아니기 때문에 코멘트를 달았습니다. 

혹시 추가적인 대화가 필요하시면 DM 부탁드립니다.

2021-10-23 10:15 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountController.java
> +        return discountList.list();
메서드는 동작/행위(Behavior)를 기대하는데 `list()`는 행위라 보기 힘들지않을까요?
리스트 요청이면 `getList()` , List로 변환을 기대한다면 `toList()`를 쓰면 좋을 것같습니다.

2021-10-23 10:22 UTC, etff approved these changes
고생하셨습니다

2021-10-24 05:22 UTC, eastshine-high approved these changes
고생하셨습니다^^

2021-10-24 05:35 UTC, hannut91 commented on src/main/java/com/kurly/promotion/ui/DiscountController.java
> +            @RequestParam(defaultValue = "0") int page,
page는 0부터 시작합니다.

2021-10-24 06:17 UTC, merged