할인 등록을 개선하라
CodeSoom/DDD-Kurly-Clone-Promotion pull request #47
Opened 2021-10-27 13:52 UTC by eastshine-high

* 할인에 기간 속성을 추가하였습니다.
* 정률 할인과 정액 할인 모두 구현되도록 하였습니다.

고민과 시행착오가 있어 PR이 조금 늦었네요.

피드백 부탁드려요.

모두 스터디 고생하셨습니다~

2021-10-27 14:15 UTC, etff commented on src/main/java/com/kurly/promotion/domain/Discount.java
> +@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
지난 PR때는 말씀을 못드렸는데, `@AllArgsConstructor` 를 썼을때 어떤점이 좋지않을까요?
혹시 설명해주실 수 있을까요?

2021-10-27 14:19 UTC, etff commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +
커맨드라는 용어는 모호합니다. 실제 주석과 용어정의가 다른 것같습니다.

2021-10-27 14:39 UTC, etff requested changes
고생하셨습니다. 생각해볼만 코멘트를 남겼습니다.

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +
커맨드 객체와 헷갈리기 때문에 힘든데요, CQRS 란 무엇인지 조사해보는 것도 좋을 것같습니다.

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +        private final Integer flatRate;
팩터리 객체가 정적 클래스일 필요가 있을까요?

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +        private final Integer flatRate;
할인 등록은 할인의 책임으로만 두는 것이 어떨까요?

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +    @Builder
특별한 의도가 있지않는이상 클래스위에 무조건적으로 롬복 어노테이션을 두는 것은 좋지 않습니다.

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/DiscountFactory.java
> +        return null;
null 을 반환하는것은 적절할지 생각해봅시다

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/FixedAmountDiscount.java
> +public class FixedAmountDiscount extends Discount {
DiscriminatorValue 는 구분값을 두기위해 씁니다. 이렇게하면 디비에 snakeCase로 들어갑니다. DB에서 어떤 형태로 저장되는지 합의가 된것일까요?

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/FixedAmountDiscount.java
> +        }
하드 코딩을 없애보면 어떨까요?
https://tecoble.techcourse.co.kr/post/2020-05-07-avoid-hard-coding/

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/FlatRateDiscount.java
> +@Entity
여기도

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/FlatRateDiscount.java
> +    public FlatRateDiscount(Period period, Integer flatRate) {
builder는 어떤 용도로 쓰면 좋을까요?

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/vo/Period.java
> +public class Period {
빈 생성자를 만드는 이유를 생각해보면 좋을 것같아요

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/domain/vo/Period.java
> + */
javadoc 주석의 마지막은 `.`로 마무리해주세요

2021-10-27 14:39 UTC, etff commented on src/main/java/com/kurly/promotion/ui/DiscountController.java
> +
실제 객체 맵핑은 쉽게 되지않습니다. 이렇게 복잡하게되면 굳이 mapper를 써야하나라는 생각도 들게됩니다.

2021-10-27 14:39 UTC, etff commented on src/test/java/com/kurly/promotion/application/DiscountServiceTest.java
> +        discountService = new DiscountService(new DiscountFactory(), discountRepository);
쓰지 않는 주석은 지워주세요

2021-10-27 14:39 UTC, etff commented on src/test/java/com/kurly/promotion/controller/DiscountControllerTest.java
> +        System.out.println(discountRegistrationData);
디버그가 필요하다면 디버깅 기능을 해보세요.
코드에 시스템 함수를 호출하지 않도록 하고 그 이유를 찾아보세요

2021-10-27 14:39 UTC, etff commented on src/test/java/com/kurly/promotion/domain/FlatRateDiscountTest.java
> +            .build();*/
여기도 주석을 지워주세요

2021-10-27 14:39 UTC, etff commented on build.gradle
> +    )
추가한 이유를 알수있을까요?

2021-10-28 16:06 UTC, etff commented
고생하셨습니다. 스터디가 종료되어 PR은 닫아도 될것같아요

2021-10-30 12:10 UTC, eastshine-high commented
> 고생하셨습니다. 스터디가 종료되어 PR은 닫아도 될것같아요

감사합니다. 혹시 마무리를 지어봐도 괜찮을까요?

2021-10-31 00:34 UTC, eastshine-high reviewed
피드백 수정하였습니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/vo/Period.java
> +package com.kurly.promotion.domain.vo;
루트 애그리게잇과의 관계 파악을 쉽게 하기 위해서 패키지를 만들어봤습니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/test/java/com/kurly/promotion/domain/FlatRateDiscountTest.java
> +            .build();*/
스터디가 마지막이라는 말에 성급히 커밋을 해버렸네요ㅜㅜ

2021-10-31 00:34 UTC, eastshine-high commented on src/test/java/com/kurly/promotion/ui/DiscountControllerTest.java
>                          .andExpect(jsonPath("$[0].productId").exists());
이 부분은 테스트 오류로 잠시 주석 처리를 하였는데요.
조회를 할 때 ``Discount``객체를 반환하면 하위 클래스``FlatRateDiscount`` 객체의 멤버 변수인 ``flatRate``는 접근을 할 수 없어서 생기는 오류인 것 같습니다.

이 문제는 어떻게 해결하는 것이 좋은 방법일까요?
JPA에서 상속 관계를 단일 테이블 전략으로 매핑했을 때, 조회를 어떻게 처리할 지를 잘 모르겠네요.

Discount 엔티티는 단일 테이블 전략으로 선언해 주었습니다.
```
@DiscriminatorColumn
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@Entity
public class Discount {
```

2021-10-31 00:34 UTC, eastshine-high commented on build.gradle
> +    )
https://mapstruct.org/documentation/stable/reference/html/#lombok
맵스트럭트를 이용할 때 롬복을 이용한 클래스가 있어 오류가 나지 않을까 해서 선언해 주었습니다.
그런데 annotationProcessor org.projectlombok:lombok는 위의 문장에도 이미 선언되어 있더라구요..
그래서 중복된 부분은 제거하였습니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +
> 커맨드라는 용어는 모호합니다. 실제 주석과 용어정의가 다른 것같습니다.

맞습니다. Discount 도메인의 입력을 책임집니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +
> 커맨드 객체와 헷갈리기 때문에 힘든데요, CQRS 란 무엇인지 조사해보는 것도 좋을 것같습니다.

Command는 CQRS가 맞습니다.
구현하기 전에 다른 DDD 프로젝트도 참고를 해보았는데요. 괜찮아 보이는 것을 사용했었는데. 이게 뭔지도 몰랐었네요ㅜㅜ

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +        private final Integer flatRate;
> 팩터리 객체가 정적 클래스일 필요가 있을까요?

이 부분은 클래스를 계층형으로 사용하고 싶어 static으로 선언하였습니다.
원하는 모양은 DiscountCommand.RegisterDiscount, DiscountCommand.ModifyDiscount 이러한 구조로요.
클래스 안에 있는 클래스의 인스턴스화를 막기 위해서 static을 선언하였습니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/DiscountCommand.java
> +        private final Integer flatRate;
> 할인 등록은 할인의 책임으로만 두는 것이 어떨까요?

네 그것도 괜찮을 것 같습니다.
개인적인 생각은 할인 클래스에서는 할인 클래스의 생성자까지만 담당하고 다른 VO클래스와의 조합은 다른 곳에서 하면 어떨까 하는 의도였습니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/DiscountFactory.java
> +        return null;
> null 을 반환하는것은 적절할지 생각해봅시다

default 문장이 있어 이 문장은 수행하지 않는데요.
null보다 빈 Discount 객체를 반환하는 것이 괜찮을까요?
다른 방법은 떠오르지 않네요.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/FixedAmountDiscount.java
> +public class FixedAmountDiscount extends Discount {
> DiscriminatorValue 는 구분값을 두기위해 씁니다. 이렇게하면 디비에 snakeCase로 들어갑니다. DB에서 어떤 형태로 저장되는지 합의가 된것일까요?

병호님과는 조금은 다르게 해보자는 의식을 너무 강하게 했던 것 같네요.
DiscriminatorValue는 coupon 도메인과 같은 값으로 수정하였습니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/FixedAmountDiscount.java
> +        }
> 하드 코딩을 없애보면 어떨까요?
> https://tecoble.techcourse.co.kr/post/2020-05-07-avoid-hard-coding/


이부분은 InvalidParameterException의 매개변수라는 생각으로 수정해 보았습니다.
```
throw new InvalidParameterException("FixedAmountDiscount.fixedAmount");
```

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/FlatRateDiscount.java
> +    public FlatRateDiscount(Period period, Integer flatRate) {
> builder는 어떤 용도로 쓰면 좋을까요?

생성자에 매개변수가 많을 때 빌더를 고려합니다.
또 인스턴스를 초기화할 때 빌더를 사용하면 의미가 분명해지는 것 같습니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/vo/Period.java
> +public class Period {
> 빈 생성자를 만드는 이유를 생각해보면 좋을 것같아요

Dozzermapper같은 API를 사용할 때 빈생성자를 필요로 했었습니다.
또 저의 경우에는 테스트를 할 때 의미를 나타낼 필요가 없는 매개변수를 생성할 때 빈생성자를 사용했습니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/ui/DiscountController.java
> +
네. 이 부분은 다른 방법도 좋아보입니다.

2021-10-31 00:34 UTC, eastshine-high commented on src/test/java/com/kurly/promotion/controller/DiscountControllerTest.java
> +        System.out.println(discountRegistrationData);
> 디버그가 필요하다면 디버깅 기능을 해보세요.
> 코드에 시스템 함수를 호출하지 않도록 하고 그 이유를 찾아보세요

네 결국 디버깅으로 해결한 것들도 좀 있었네요.

2021-10-31 00:34 UTC, eastshine-high commented on src/main/java/com/kurly/promotion/domain/Discount.java
> +@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@AllArgsConstructor이 위험한 이유는 클래스의 필드 변수 위치가 바뀔 경우, 이 생성자를 사용하는 측에서 순서가 바뀐 것을 인지하지 못할 수도 있는 점입니다.

2021-11-01 13:55 UTC, closed without merging